export const SERVICE_KEYS = {
  TODO_REPOSITORY: Symbol.for("TODO_REPOSITORY"),
  TODO_STORE: Symbol.for("TODO_STORE"),
  NOTIFICATION_STORE: Symbol.for("NOTIFICATION_STORE"),
  PENDING_REQUEST_STORE: Symbol.for("PENDING_REQUEST_STORE"),
};
