export const SERVICE_KEYS = {
  AUTH_SERVICE: Symbol.for("AUTH_SERVICE"),
  AUTH_STORE: Symbol.for("AUTH_STORE"),
  TODO_REPOSITORY: Symbol.for("TODO_REPOSITORY"),
  TODO_STORE: Symbol.for("TODO_STORE"),
  NOTIFICATION_STORE: Symbol.for("NOTIFICATION_STORE"),
  PENDING_REQUEST_STORE: Symbol.for("PENDING_REQUEST_STORE"),
  CATEGORY_REPOSITORY: Symbol.for("CATEGORY_REPOSITORY"),
  CREATE_CATEGORY_SERVICE: Symbol.for("CREATE_CATEGORY_SERVICE"),
};
