name: Deploy to Azure Web App

on:
  push:
    branches:
      - main # Replace with the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: notebase.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          chmod +x ./build_docker_image.sh
          ./build_docker_image.sh

      - name: Tag Docker image
        run: docker tag notebase:latest notebase.azurecr.io/notebase:latest

      - name: Push Docker image
        run: docker push notebase.azurecr.io/notebase:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: notebase
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: notebase.azurecr.io/notebase:latest
